Install missing dependency
Otherwise `pnpm run dev` was printing

    Error: The following dependencies are imported but could not be resolved:

      @tanstack/query-core (imported by /.../vike-react-query/pages/posts/index/+Page.tsx)